# problem 1

In [ ]:
import torch

In [4]:
r1 = -5
r2 = 5
t = (r1 - r2) * torch.rand((4,4)) + r2
t

tensor([[-2.1713,  1.2228,  4.3242,  3.6092],
        [-4.3589, -2.6548, -0.1833,  4.9067],
        [-2.8525,  1.7715, -3.2862,  4.4248],
        [ 3.9071, -2.6506, -3.7095, -1.2570]])

# problem 2

In [2]:
import torch

In [3]:
a = torch.arange(8).reshape((2,2,2))
a

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [5]:
a.flatten(0, 1).reshape((2,2,2))

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])